### ISSUE TITLE
plan to share the algorithm？

### ISSUE THREAD

**Issue by x2ss** [DI-HGR/cross_domain_gesture_dataset#1]
Hi，

Impressive work！ 

Will you have plan to share your signal processing flow and deep learning model？

Best

**Comment by EastLYD** [comment]
I am not sure yet. The code is written by our team and we will discuss about that after the paper is accepted.
Thanks for your attention!

**Comment by DI-HGR** [comment]
I am not sure yet. The code is written by our team and we will discuss about that after the paper is accepted.
Thanks for your attention!

**Comment by x2ss** [comment]
> I am not sure yet. The code is written by our team and we will discuss about that after the paper is accepted. Thanks for your attention!

Thanks for your reply. Hope that your paper will be accepted!

Best

**Comment by Hongki-Long** [comment]
Thank you for your generous sharing!

Will you share the row dataset?
Best

**Comment by DI-HGR** [comment]
> Thank you for your generous sharing!
> 
> Will you share the raw dataset? Best

The size of the raw dataset is about 700GB and we cannot find a flexible solution to share such a large dataset. But we would like to make it public if you have some good ideas!

**Comment by Hongki-Long** [comment]
First of all, thank you very much for your reply! If you can register an
account of aliyundrive, the url is
www.aliyundrive.com, it should help you solve this problem. Thank you again!

x2ss ***@***.***>于2021年11月28日 周日17:43写道：

**Comment by DI-HGR** [comment]
> First of all, thank you very much for your reply! If you can register an account of aliyundrive, the url is [www.aliyundrive.com](http://www.aliyundrive.com), it should help you solve this problem. Thank you again!

Thanks for your suggestion. I have address this problem and you can download the raw dataset from the following website: 
https://rec.ustc.edu.cn/share/b5999300-564b-11ec-96cb-29f7856f340e

**Comment by GaoxiangLuo** [comment]
Hi, the link toward the raw dataset expired. If it's not too much of a hassle, would you mind sharing it again? Thanks.
